#! /bin/sh

# startup stuff
sxhkd &
picom & 
dunst &
sh .config/bspwm/polybar.sh &
sh .config/bspwm/xconf.sh &
nitrogen --restore &

# хз
bspc monitor "eDP-1" -s "HDMI-1"

bspc monitor eDP-1 -d 1 2 3 4 
bspc monitor HDMI-1 -d 5 6 7 8
 
bspc config wm_name LG3D
bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action2 resize_corner


# window borders
bspc config border_width        "3"
bspc config window_gap          "6"
bspc config normal_border_color "#000000CC"
bspc config active_border_color "#fbf1c7"
bspc config focused_border_color "#fbf1c7"
bspc config presel_feedback_color "#000000CC"

