#! /bin/sh
# programs to launch
sxhkd &
picom & 
polybar &
nitrogen --restore &
xsettingsd &
xrandr --output HDMI-A-0 --set TearFree on &
xinput --set-prop 10 'libinput Accel Speed' -0.7 &
xinput --set-prop 20 'libinput Accel Speed' -0.7 &
setxkbmap -option grp:alt_shift_toggle us,ru &



# desktop
bspc monitor -d 1 2 3 4 5


# 
bspc config wm_name LG3D
bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# window borders
bspc config border_width        "3"
bspc config window_gap          "6"
bspc config normal_border_color "#282828"
bspc config active_border_color "#8ec07c"
bspc config focused_border_color "#8ec07c"
bspc config presel_feedback_color "#282828"





